### PR TITLE
Null-safety

### PR DESCRIPTION
**Pull request by muccy**
Migrated package to null-safety.
This time it should be better to make a new Pub.dev release

### CODE REVIEW

**Comment by TheR00st3r** [comment]
Hi,
are there any plans to merge and release this PR?

**Comment by olyshchuk** [comment]
Hello @24601, could you PLEASE merge this PR?

**Comment by 24601** [comment]
@olyshchuk - Done, sorry for the delay. 

@muccy - thank you for your contribution, will do a release shortly.

**Comment by 24601** [comment]
@TheR00st3r - done:

```icons_helper: ^1.2.0-nullsafety.1```

**Pull request merged**
