### PR TITLE
Restore functionality

### PR DESCRIPTION
**Pull request by muccy**
Hi,
this pull request is far from complete (I haven't check new FontAwesome icons), but in works with latest Flutter and `font_awesome_flutter` versions

### CODE REVIEW

**Review by michaelomah — APPROVED** [review]

**Review by michaelomah — APPROVED** [review]

**Comment by michaelomah** [comment]
@rohansingh Can we get this PR merged?

**Comment by rohansingh** [comment]
@michaelomah Sounds good to me but I don't have permission to merge.

**Comment by michaelomah** [comment]
@rohansingh Ah, my bad.

@24601 Can we get this PR merged?

**Comment by 24601** [comment]
> @rohansingh Can we get this PR merged?

Done! Thanks!

**Pull request merged**
